[server]
maxUploadSize = 5

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#111111"
backgroundColor = "#F7F7F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#121212"
font = "sans serif"
